# Generated by Django 5.2.3 on 2025-08-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('commodity', '0002_remove_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
