# Generated by Django 5.2.3 on 2025-09-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping_cart', '0002_cart_color_cart_quantity_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
