# Generated by Django 5.2.3 on 2025-09-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping_cart', '0003_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
